### PR TITLE
change event collector to pass client_addr instead of REMOTE_ADDR

### PR DESCRIPTION
**Pull request by Kaitaan**
note: I have no idea if this is correct; hoping someone can give me a little guidance here.  I have not tested this code at all.  I can't run the tests without a lot of overhead work. They require baseplate, which requires linux (or, at least, not OSX, near as I can tell), which requires me to setup and install a vm just to run the tests.

:eyeglasses: @spladug @dellis23

### CODE REVIEW

**Comment by spladug** [comment]
> They require baseplate, which requires linux (or, at least, not OSX, near as I can tell), which requires me to setup and install a vm just to run the tests.

yup, we have some vagrant files that can help if you want.

**Comment by spladug** [comment]
test suite runs fine minus `test_max_length_enforced` which needs a `request.client_addr` as well.  I'll try to get travis up and running here shortly.

**Comment by spladug** [comment]
:nail_care:

**Comment by Kaitaan** [comment]
:haircut:

**Comment by spladug** [comment]
:fish: ! thanks for doing this

**Comment by dellis23** [comment]
:fish: 

I tried running the tests but can't import `message_queue` from baseplate.  I have the latest version from the PPA as well.

**Comment by spladug** [comment]
squashed and merged as 78da5e49d97f04dc8316782e51cbacfb44292a02. thanks!

(and there's travis on here now)

**Pull request closed without merging**
